### ISSUE TITLE
Configure link in README is broken

### ISSUE THREAD

**Issue by molovo** [probot/no-response#1] opened 2017-05-22 11:38 UTC
The URL https://github.com/integration/probot-no-response returns a 404 error

**Comment by lee-dohm** [comment] 2017-05-24 18:36
Thanks, I'm aware :grinning: I'm just trying to get the integration to its permanent home and then it will go live.

**Comment by Glavin001** [comment] 2017-05-27 20:48
Is the [probot's `stale` package](https://github.com/probot/stale) is better suited than this? It still has a working link: https://github.com/apps/probot-stale

**Comment by lee-dohm** [comment] 2017-05-28 04:49
It depends on your use case. I'm talking with @bkeepers about potentially rolling the functionality here into probot/stale.

**Comment by jsquyres** [comment] 2017-07-14 20:23
The link is no longer a 404, but it does return that probot-no-response is a private integration.  Is this intended?

![probot-no-response](https://user-images.githubusercontent.com/617316/28229433-c08131c6-68b0-11e7-9b27-6bf585831bc2.png)

I ask because we'd love to use this probot in the Open MPI github organization.  😄

**Comment by j-f1** [comment] 2017-10-18 15:01
Any update on this, @lee-dohm? I’d love to see this used on desktop/desktop.

**Comment by bkeepers** [comment] 2017-10-24 13:06
I deployed an instance of this yesterday, but it looks like the app doesn't actually work: http://github.com/apps/no-response.

I'll try to dive into the code today or tomorrow to see what's going on.

**Comment by atian25** [comment] 2017-10-29 07:47
@bkeepers hi, is this fixed now ?

**Comment by bkeepers** [comment] 2017-10-29 14:10
Nope. I dug for awhile, but there's still more work to do.

@lee-dohm did you make any progress on Friday? Would you want to get a PR open with your local changes?

**Comment by lee-dohm** [comment] 2017-10-29 18:02
@bkeepers Yes, I tested it on Friday via localtunnel and everything appeared to be working after the rewrite, see the test here: https://github.com/lee-dohm/bot-test/issues/6

Like probot-stale, probot-no-response requires a configuration file to begin working. Did you add one to your test repo, @bkeepers?

**Comment by olstenlarck** [comment] 2017-11-02 16:43
> requires a configuration file to begin working

That not sounds good. Is this required? Why not some defaults?

**Comment by lee-dohm** [comment] 2017-11-02 17:39
> Why not some defaults?

@olstenlarck It [has defaults](https://github.com/probot/no-response/blob/master/lib/defaults.js). We decided that bots that do things like close issues should [wait to perform their job until there is an explicit configuration file.](https://github.com/probot/stale/pull/15) This prevents accidents like the following:

1. Install the GitHub app on your repo intending to customize it
1. The app launches, closing hundreds of issues
1. You add your custom configuration file which would reduce the hundreds of applicable issues to a tiny number
1. You have to go back and clean up hundreds of issues that the app touched

**Comment by j-f1** [comment] 2017-11-02 18:16
Could the bot automatically open a PR when installed that adds a default config file, and say why this is necessary in the description?

**Comment by olstenlarck** [comment] 2017-11-02 18:29
@lee-dohm hm, good point. I'm agree.

Sending initial configuration PR sounds good too.

**Comment by bkeepers** [comment] 2017-11-03 00:23
> @bkeepers Yes, I tested it on Friday via localtunnel and everything appeared to be working after the rewrite…

Doh, sorry, I missed the rewrite PR. Awesome to see this working now. Want to submit a PR to add it to the website? https://github.com/probot/probot.github.io/blob/master/CONTRIBUTING.md#adding-your-app

**Comment by lee-dohm** [comment] 2017-11-03 00:44
@j-f1 The problem is that it is impossible to determine the intent of the person installing the app from them simply installing the app. For example, I installed probot-stale on the entire Atom organization but I only wanted to enable it in one repo at first and then roll it out to the others over time. Should it have opened approximately 200 PRs, one on every repo, assuming that is what I wanted?

Personally, I think the current system is the best compromise.

@bkeepers Yep, I'll add it :+1:

**Closed** 2017-11-13 22:25 UTC
Labels: bug
